config/routes.rb
Rails.application.routes.draw do
  get 'bbs/show'
  post 'bbs/add'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bbs_controller.rb
class BbsController < ApplicationController
  def show
    @messages = Message.all
  end

  def add
    Message.create(
      text: params[:text],
      userid: 0 # debug
    )

    redirect_to action: 'show'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bbs_helper.rb
module BbsHelper
end

app/views/bbs/show.html.erb
<h1>BBS messages</h1>
<div>
  <% @messages.each do |msg| %>
    <div> <%= msg.text %></div>
  <% end %>
</div>

<div>
  <%= form_with url: bbs_add_path do |f| %>
    <%= f.text_field :text %>
    <%= f.submit "Add" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleBbs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>